import mongoose from 'mongoose';

const OrderSchema = new mongoose.Schema({
  id: { type: String, required: true, unique: true },
  customerUid: { type: String, required: true },
  customerName: { type: String, required: true },
  customerPhone: { type: String, required: true },
  vendorId: { type: String, required: true },
  vendorName: { type: String, required: true },
  vendorPhone: { type: String },
  customerAddress: { type: String },
  customerLandmark: { type: String },
  vendorLandmark: { type: String },
  vendorAddress: { type: String },
  items: { type: String, required: true },
  itemsPrice: { type: Number, required: true },
  riderFee: { type: Number, required: true },
  totalPrice: { type: Number, required: true },
  status: { type: String, required: true },
  color: { type: String, required: true },
  time: { type: Date, default: Date.now },
  createdAt: { type: Date, default: Date.now },
  riderUid: { type: String },
  riderName: { type: String },
  riderPhone: { type: String },
  pickupAddress: { type: String },
  code1: { type: String },
  code2: { type: String },
  code3: { type: String },
  code4: { type: String },
  handoverCode: { type: String },
  readyForDeliveryAt: { type: Date },
  washingAt: { type: Date },
  readyAt: { type: Date },
  pickedUpAt: { type: Date },
  pickedUpDeliveryAt: { type: Date },
  paidAt: { type: Date },
  deliveredAt: { type: Date },
  completedAt: { type: Date },
  penaltyApplied: { type: Boolean, default: false },
  payoutReleased: { type: Boolean, default: false },
  disputed: { type: Boolean, default: false },
  isLocked: { type: Boolean, default: false },
  lockedBy: { type: String },
  lockExpires: { type: Number },
  returnReason: { type: String },
  consecutiveReturns: { type: Number, default: 0 },
  paymentMethod: { type: String, enum: ['wallet', 'transfer', 'card'], default: 'wallet' }
});

export default mongoose.models.Order || mongoose.model('Order', OrderSchema);
